{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "baed10a0-49df-4633-bc9d-c5ec87922b46",
   "metadata": {},
   "source": [
    "# Introduction to TMS and Motor Thresholds \n",
    "\n",
    "Authored by Remy Cohan [cohanR.github.io] with minor edits - mostly formatting - by Peter Kohler [kohlerlab.com].\n",
    "\n",
    "As discussed during the lecture and as you saw in the video we played during class (also available on eClass), in TMS research, we often measure motor thresholds (MTs) using single-pulse TMS to primary motor cortex (M1). The resting motor threshold (rMT) is defined as the minimum TMS intensity that produces an electromyographic (EMG) response of 50 µV in a relaxed muscle. MTs are an important measure because they can reflect changes in neural excitability and plasticity.\n",
    "\n",
    "On the other hand, repetitive TMS (rTMS) is a different technique where multiple pulses are delivered in patterns (e.g., 1 Hz, 10 Hz, or theta burst stimulation). rTMS is gaining popularity as a potential treatment for neuropsychiatric conditions and in neurorehabilitation.\n",
    "\n",
    "To study the effects of rTMS, we can measure MTs using single-pulse TMS before and after an rTMS protocol. This allows us to see how the rTMS protocol changes neural activity in a specific brain area, which is critical when designing treatment protocols.\n",
    "\n",
    "Remember the distinction:\n",
    "\n",
    "* Single-pulse TMS: Measures MTs and neural excitability in primary motor cortex (M1).\n",
    "    \n",
    "* Repetitive TMS (rTMS): Modulates neural activity to induce plasticity.\n",
    "    \n",
    "In the data below, pre-rTMS refers to a baseline single-pulse TMS measure of MTs before the rTMS protocol. Post-rTMS refers to the same measure after the rTMS protocol.\n",
    "\n",
    "This background should help you interpret the data and answer the following questions.\n",
    "\n",
    "**It is a good idea to review some of Panda's functions such as groupby and .agg here:** https://github.com/marsja/jupyter/blob/master/pandas_groupby_tutorial.ipynb\n",
    "\n",
    "One more thing: in real TMS datasets, before you interpret anything, you do quick sanity checks (missing values, duplicates, and obviously weird threshold values). That’s what we’re doing here — this is neuroscience, not a pure coding exercise."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4029999e-b3f0-4469-9178-4ad412947d56",
   "metadata": {},
   "source": [
    "## Preample: Import some packages \n",
    "\n",
    "As in often the case, we start our code by importing some Python modules. \n",
    "\n",
    "In this case, we import the pandas module, which is a powerful data manipulation library and scipy which we use for our correlation analysis. \n",
    "We also import modules for plotting, matplotlib and seaborn. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "5aecb584-dcc6-41cf-a634-a1a0fd831d83",
   "metadata": {},
   "outputs": [],
   "source": [
    "# install tools for getting data off osf, and for fitting the data\n",
    "try:\n",
    "  import google.colab\n",
    "  IN_COLAB = True\n",
    "except:\n",
    "  IN_COLAB = False\n",
    "if IN_COLAB:  \n",
    "    import shutil\n",
    "    # download github repository to get access to the tms data\n",
    "    shutil.rmtree(\"NRSC2200\", ignore_errors=True)\n",
    "    !git clone https://github.com/pjkohler/NRSC2200\n",
    "    # add tms directory to path\n",
    "    datapath = \"NRSC2200/tms/tms_cohan_data.csv\"\n",
    "else:\n",
    "    datapath = \"tms_cohan_data.csv\"\n",
    "# import python modules to use for analysis\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from scipy.stats import pearsonr"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4025ea62",
   "metadata": {},
   "source": [
    "## Question 1: Data Inspection + basic TMS sanity checks (1 point)\n",
    "\n",
    "How many pre- and post data points are present in the dataset?\n",
    "\n",
    "To answer this, load the dataset and count the number of available data points for the pre_rMT and post_rMT columns.\n",
    "\n",
    "But don’t be a robot about it. Before you interpret anything in a TMS threshold dataset, you do two quick checks:\n",
    "\n",
    "1) Are the columns you need actually there?\n",
    "2) Are there obviously impossible / suspicious rMT values?\n",
    "\n",
    "**For this homework, treat rMT values < 20 or > 95 as suspicious** (this is not a law of nature, it’s just a reasonable QC flag for a teaching dataset).\n",
    "\n",
    "Please include only the lines of code that you changed, in your submitted answer."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fd837688",
   "metadata": {},
   "outputs": [],
   "source": [
    "# load the dataset\n",
    "data = pd.read_csv(datapath)\n",
    "\n",
    "# print column names from the data (csv file):\n",
    "\n",
    "# Where ever you see this \"# add your code here\" you need to add your answer \n",
    "\n",
    "# in this first example, we are going to give you the answer:\n",
    "\n",
    "print(\"column names:\", # add your code here )    # answer: data.columns.tolist()\n",
    "\n",
    "# NEW: basic required-column check (if this fails, nothing else matters)\n",
    "required_cols = ['participant_id', 'condition', 'sex', 'age', 'pre_rMT', 'post_rMT']\n",
    "missing_required = [c for c in required_cols if c not in data.columns]\n",
    "print(\"missing required columns:\", missing_required)\n",
    "\n",
    "# NEW: quick look at labels (helps catch dumb mistakes later)\n",
    "print(\"conditions present:\", # add your code here )\n",
    "print(\"sex labels present:\", # add your code here )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0a5ee5c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Using the variable names pre_count and post_count, count the number of pre- and post-rMT data points and print the answer\n",
    "# Hint: Use .notna() to check for missing values before counting.\n",
    "\n",
    "# fill in the function to count non-null values for pre_rMT\n",
    "pre_count = # add your code here\n",
    "\n",
    "# fill in the function to count non-null values for post_rMT      \n",
    "post_count =  # add your code here\n",
    "\n",
    "# if the code you added above are correct, running this section should print out the answers\n",
    "print(f\"number of Pre rMT data points: {pre_count}\")\n",
    "print(f\"number of Post rMT data points: {post_count}\")\n",
    "\n",
    "# NEW: suspicious-value QC flags (rMT < 20 or > 95)\n",
    "n_suspicious_pre = # add your code here\n",
    "n_suspicious_post = # add your code here\n",
    "\n",
    "print(\"suspicious pre_rMT values (<20 or >95):\", n_suspicious_pre)\n",
    "print(\"suspicious post_rMT values (<20 or >95):\", n_suspicious_post)\n",
    "\n",
    "# NEW: duplicate participant rows check (if a participant appears more than once, that changes how you interpret results)\n",
    "dup_participants = # add your code here\n",
    "print(\"participants appearing more than once:\")\n",
    "print(dup_participants)\n",
    "\n",
    "# NEW: quick numeric signature so your TA can tell you ran the cell (not a trick, just accountability)\n",
    "sig_q1 = int(pre_count * 3 + post_count * 5 + n_suspicious_pre * 7 + n_suspicious_post * 11)\n",
    "print(\"Q1 signature:\", sig_q1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0368d9d9",
   "metadata": {},
   "source": [
    "## Question 2: Check for missing values (1 point)\n",
    "\n",
    "Missing values are a big deal in TMS threshold work (coil placement drift, EMG noise, participant discomfort, etc.).\n",
    "\n",
    "1) Report missing values for each column.\n",
    "2) Then answer this (choose one letter):\n",
    "\n",
    "**Which is more consistent with missing rMT values in a motor threshold dataset?**\n",
    "\n",
    "A) technical/acquisition issue (e.g., EMG noise, poor relaxation, coil positioning)\n",
    "\n",
    "B) missing values are expected and do not matter\n",
    "\n",
    "C) missing values prove the rTMS protocol worked\n",
    "\n",
    "Please include only the lines of code that you changed, in your submitted answer (and the letter you chose)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3394fa6d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# fill in the function to check for missing values in the data\n",
    "# hint: The .isnull().sum() method shows missing values for each column.\n",
    "\n",
    "missing_values =  # add your code here \n",
    "\n",
    "# if the code you added above is correct, running this section should print out the answers\n",
    "print(\"missing values in each column:\")\n",
    "print(missing_values)\n",
    "\n",
    "# NEW: which column has the most missing values?\n",
    "most_missing_col = # add your code here\n",
    "most_missing_n = # add your code here\n",
    "print(\"most missing column:\", most_missing_col)\n",
    "print(\"missing count:\", most_missing_n)\n",
    "\n",
    "# NEW: quick numeric signature for TA\n",
    "sig_q2 = int(most_missing_n * 13 + len(missing_values) * 17)\n",
    "print(\"Q2 signature:\", sig_q2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "884c7e7f-6c46-463f-8aa6-f66a401d5b20",
   "metadata": {},
   "source": [
    "## Question 3: Participant Demographics + threshold characterisation (2 point)\n",
    "\n",
    "What are the demographic statistics of the participants?\n",
    "\n",
    "Specifically:\n",
    "\n",
    "1) How many males and females are there in the dataset?\n",
    "\n",
    "2) What are the mean and standard deviation of **age**, **pre-rMT**, and **post-rMT** values **separately for Active vs Sham**?\n",
    "\n",
    "3) Compute the mean change score (post − pre) for Active and Sham. In TMS terms, a decrease in rMT means less stimulator output is needed to trigger a response (so excitability is higher).\n",
    "\n",
    "Your outputs must be printed exactly by the code: sex_counts, stats_summary, and delta_summary."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f44977c0-bfaa-4490-a1b6-957d9afeae32",
   "metadata": {},
   "outputs": [],
   "source": [
    "# add code to count males and females\n",
    "# hint: The .value_counts() function helps count categorical variables.\n",
    "\n",
    "sex_counts = # add your code here  \n",
    "\n",
    "# if the code you added above is correct, running this section should print out the answers\n",
    "print(\"count of participants by sex:\")\n",
    "print(sex_counts)\n",
    "\n",
    "# compute mean and standard deviation for age, pre-rMT, and post-rMT values by condition\n",
    "# hint: Use .groupby() to separate data by condition before applying statistics.\n",
    "\n",
    "stats_summary = # add your code here  \n",
    "\n",
    "# if the function you added above is correct, running this section should print out the answers\n",
    "print(\"mean and standard deviation for Age, Pre MTs, and Post MTs by condition:\")\n",
    "print(stats_summary)\n",
    "\n",
    "# NEW: change score (post - pre) by condition\n",
    "data['delta_rMT'] = data['post_rMT'] - data['pre_rMT']\n",
    "delta_summary = # add your code here\n",
    "print(\"mean and standard deviation for ΔrMT (post - pre) by condition:\")\n",
    "print(delta_summary)\n",
    "\n",
    "# NEW: quick numeric signature for TA\n",
    "sig_q3 = round(float(delta_summary.select_dtypes(include=[np.number]).values.sum()), 3)\n",
    "print(\"Q3 signature:\", sig_q3)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c108adb9-d1e1-40e0-9b0f-aacdef51324c",
   "metadata": {},
   "source": [
    "## Question 4: Pre vs post rMT values by Condition (1 point)\n",
    "\n",
    "How do the pre- and post-rMT values compare between the active and sham conditions?\n",
    "\n",
    "Make the same plot as before, but now add one more plot that is more \"TMS-like\": a within-participant plot.\n",
    "\n",
    "Why? Because in TMS we often care about whether **individual participants** shift pre → post, not just group medians.\n",
    "\n",
    "Your tasks:\n",
    "\n",
    "1) Create the boxplot as before.\n",
    "\n",
    "2) Create a within-participant line plot where each participant has a line from pre to post, separated by condition.\n",
    "\n",
    "3) Print the mean change (post − pre) for Active and Sham (you already computed delta_rMT in Q3, so use it).\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "699dc006-3b6a-4b30-8b7f-7e91b3febd99",
   "metadata": {},
   "outputs": [],
   "source": [
    "# create boxplot comparing pre- and post-rMT values by condition\n",
    "# hint: Convert data into long format using pd.melt() before plotting.\n",
    "\n",
    "# in the code snippet below, where ever you see 3 hastags (###) add the correct column name for the correct plotting of the data\n",
    "\n",
    "tms_data = pd.melt(data, id_vars =['participant_id', ###],  \n",
    "                      value_vars=[###, ###],            \n",
    "                      var_name='time', value_name='rMT')\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.boxplot(x='condition', y='rMT', hue='time', data=tms_data, palette='Set2')\n",
    "plt.title(\"Pre vs Post rMT by Condition\")\n",
    "plt.xlabel(\"Condition\")\n",
    "plt.ylabel(\"rMT (TMS dose)\")\n",
    "plt.legend(title=\"Time\")\n",
    "plt.show()\n",
    "\n",
    "# NEW: within-participant change plot (each line = one participant)\n",
    "plt.figure(figsize=(10, 6))\n",
    "sns.lineplot(data=tms_data, x='time', y='rMT', hue='condition', units='participant_id', estimator=None, alpha=0.35)\n",
    "plt.title(\"Within-participant pre → post rMT (each line = one participant)\")\n",
    "plt.xlabel(\"Time\")\n",
    "plt.ylabel(\"rMT (TMS dose)\")\n",
    "plt.show()\n",
    "\n",
    "# Print mean change by condition (post - pre)\n",
    "mean_change = # add your code here\n",
    "print(\"Mean change (post - pre) by condition:\")\n",
    "print(mean_change)\n",
    "\n",
    "# NEW: rule-based conclusion label (TA-friendly)\n",
    "# If Active mean change is at least 1.0 lower than Sham, label = 'Active decreases more'\n",
    "# If Active mean change is at least 1.0 higher than Sham, label = 'Active increases more'\n",
    "# Otherwise label = 'Similar'\n",
    "diff_change = float(mean_change.loc['active'] - mean_change.loc['sham']) if ('active' in mean_change.index and 'sham' in mean_change.index) else np.nan\n",
    "if np.isfinite(diff_change) and diff_change <= -1.0:\n",
    "    label = 'Active decreases more'\n",
    "elif np.isfinite(diff_change) and diff_change >= 1.0:\n",
    "    label = 'Active increases more'\n",
    "else:\n",
    "    label = 'Similar'\n",
    "print(\"Q4 conclusion label:\", label)\n",
    "\n",
    "# NEW: quick numeric signature for TA\n",
    "sig_q4 = round(float(mean_change.sum()), 3) if hasattr(mean_change, 'sum') else None\n",
    "print(\"Q4 signature:\", sig_q4)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e56bea0a-1d4d-4c8d-9ce0-829fd28cb4ea",
   "metadata": {},
   "source": [
    "## Question 5: Correlation between Age and baseline rMT (2 points)\n",
    "\n",
    "Run the code below to plot age against baseline rMT - no need to make any changes to the code.\n",
    "\n",
    "But don’t just say \"looks significant\" like it’s a stats course.\n",
    "\n",
    "Your tasks:\n",
    "\n",
    "1) Report r (Pearson correlation) and p-value.\n",
    "\n",
    "2) Categorise the strength of the relationship using this rule:\n",
    "\n",
    "- Weak: |r| < 0.30\n",
    "\n",
    "- Moderate: 0.30 ≤ |r| < 0.50\n",
    "\n",
    "- Strong: |r| ≥ 0.50\n",
    "\n",
    "3) Choose ONE direction (A/B/C):\n",
    "\n",
    "A) older age is associated with higher baseline rMT\n",
    "\n",
    "B) older age is associated with lower baseline rMT\n",
    "\n",
    "C) no clear association (if your relationship is Weak)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "db133532-5dce-43bf-a8aa-980bf9abc561",
   "metadata": {},
   "outputs": [],
   "source": [
    "# correlation plot for age vs pre rMTs\n",
    "corr, pval = pearsonr(data['age'], data['pre_rMT'])\n",
    "\n",
    "plt.figure(figsize=(8, 6))\n",
    "sns.regplot(x='age', y='pre_rMT', data=data, scatter_kws={'s': 50, 'alpha': 0.7, 'clip_on': False}, color='green')\n",
    "plt.title(\"age vs baseline rMT \")\n",
    "plt.xlabel(\"age (years)\")\n",
    "plt.ylabel(\"baseline rMT\")\n",
    "plt.xlim(20, 60)\n",
    "plt.ylim(45, 75)\n",
    "plt.text(35, 50, f\"correlation between age and pre rMT:\\nr = {corr:.2f}\", fontsize=12)\n",
    "plt.show()\n",
    "\n",
    "# NEW: print r and p-value for your written answer\n",
    "print(\"Pearson r:\", round(corr, 3))\n",
    "print(\"p-value:\", round(pval, 4))\n",
    "\n",
    "# NEW: strength category (rule-based)\n",
    "abs_r = abs(corr)\n",
    "if abs_r < 0.30:\n",
    "    strength = 'Weak'\n",
    "elif abs_r < 0.50:\n",
    "    strength = 'Moderate'\n",
    "else:\n",
    "    strength = 'Strong'\n",
    "print(\"Strength category:\", strength)\n",
    "\n",
    "# NEW: direction choice helper (still requires you to choose A/B/C in your write-up)\n",
    "direction = 'positive' if corr > 0 else 'negative'\n",
    "print(\"Direction (sign of r):\", direction)\n",
    "\n",
    "# NEW: quick numeric signature for TA\n",
    "sig_q5 = round(float(corr * 1000 + pval * 10000), 2)\n",
    "print(\"Q5 signature:\", sig_q5)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "60d1652e-b609-4bad-9a81-4bc78457a328",
   "metadata": {},
   "source": [
    "## Question 6: Interpretation (2 points)\n",
    "\n",
    "This is where you show you understand what rMT actually means.\n",
    "\n",
    "Use your outputs from Q3/Q4 (mean change post − pre by condition) and Q5 (correlation strength category).\n",
    "\n",
    "Answer using this exact format (no essays):\n",
    "\n",
    "1) **rTMS effect on excitability (choose one):**\n",
    "\n",
    "A) If rMT decreases post-rTMS, excitability increased (less intensity needed)\n",
    "\n",
    "B) If rMT decreases post-rTMS, excitability decreased\n",
    "\n",
    "C) rMT cannot tell you anything about excitability\n",
    "\n",
    "2) **Age statement (choose one):**\n",
    "\n",
    "D) Age likely matters for baseline rMT in this dataset (Moderate/Strong)\n",
    "\n",
    "E) Age likely does not matter much for baseline rMT in this dataset (Weak)\n",
    "\n",
    "3) One sentence only that uses your numbers (ΔActive, ΔSham, and your strength category).\n",
    "\n",
    "Your TA is not here to read fan fiction. Keep it tight."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "q6_helper_cell",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q6 helper (do not edit): prints the exact numbers you must reference\n",
    "if 'delta_rMT' not in data.columns:\n",
    "    data['delta_rMT'] = data['post_rMT'] - data['pre_rMT']\n",
    "\n",
    "q6_means = data.groupby('condition')[['pre_rMT', 'post_rMT', 'delta_rMT']].mean().round(3)\n",
    "print(\"Means by condition (pre, post, delta):\")\n",
    "print(q6_means)\n",
    "\n",
    "sig_q6 = round(float(q6_means.values.sum()), 3)\n",
    "print(\"Q6 signature:\", sig_q6)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "teaching",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
